language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      # Travis by default is 64 bit so we toggle to use the 32 bit libs
      env: MAVEN_PROFILE="-DosDetection=false -Plinux-x86_32"
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - cmake
            - gcc-multilib
    - os: osx
      osx_image: xcode10.1
# Java is not yet supported on the Windows Build Environment
#    - os: windows
#      jdk: oraclejdk11

install: true
script:
  - mvn -N io.takari:maven:wrapper
  - |-
    export PATH=`./mvnw -v |awk -F ': ' '{print $2}' |sed -n 2p`/bin:$PATH
  - ./mvnw -V install $MAVEN_PROFILE

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: change
